/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5ad3007390b40a2b2d5f45fc
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { DipendenteService } from '../../services/dipendente.service';
// Import Models
import { Dipendente } from '../../domain/demo1_db/dipendente';
import { User } from '../../domain/demo1_db/user';

// START - USED SERVICES
/**
* DipendenteService.create
*	@description CRUD ACTION create
*
* DipendenteService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id resource
*
* DipendenteService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a Dipendente
 */
@Component({
    selector: 'app-dipendente-edit',
    templateUrl: 'dipendente-edit.component.html',
    styleUrls: ['dipendente-edit.component.css']
})
export class DipendenteEditComponent implements OnInit {
    item: Dipendente;
    listUtenti: User[];
    model: Dipendente;
    formValid: Boolean;

    constructor(
    private dipendenteService: DipendenteService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new Dipendente();
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.dipendenteService.get(id).subscribe(item => this.item = item);
            }
            // Get relations
            this.userService.list().subscribe(list => this.listUtenti = list);
        });
    }


    /**
     * Save Dipendente
     *
     * @param {boolean} formValid Form validity check
     * @param Dipendente item Dipendente to save
     */
    save(formValid: boolean, item: Dipendente): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.dipendenteService.update(item).subscribe(data => this.goBack());
            } else {
                this.dipendenteService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



